### ISSUE TITLE
Resolve the alternative implementations for Autocomplete control

### ISSUE THREAD

**Issue by adriatic** [aurelia-widgets/aurelia-kendoui#20]
Jedd offers **[two options](https://github.com/aurelia-widgets/aurelia-kendoui/wiki/autocomplete#proposed-options)** for Autocomplete control implementation - **and for the whole class that behave like Autocomplete**.

We should decide which way to go as soon as we believe that we understand all controls.

**Comment by jedd-ahyoung** [comment]
I don't know if we came to a consensus on this. I'd advocated that everything be a custom element, but there was an argument for custom attributes as well. I can write the document for Autocomplete, but until we reach a consensus (or I or someone else simply pulls the trigger) this will be outstanding.

**Comment by adriatic** [comment]
In reference to [above comment](https://github.com/aurelia-widgets/aurelia-kendoui/issues/20#issuecomment-148238312)
Since the moment  learned that creating dynamic views for custom elements is easy and feasible, I would also advocate that everything is a custom element. 

Let's move forward with this issues settled
