### ISSUE TITLE
This app should not use bootstrap classes nor components

### ISSUE THREAD

**Issue by adriatic** [aurelia-widgets/aurelia-kendoui#6]
Our goal with this app (and subsequent conversion into Aurelia plugin) should be equally focused on getting endorsement from Aurelia **and** Telerik. So we should make sure that it uses only KendoUI controls (at the moment we inherited nav-bar from Aurelia Navigation Skeleton.

**Comment by jedd-ahyoung** [comment]
I'll add this to the wiki so that we can close this issue.

**Comment by jedd-ahyoung** [comment]
Referenced here: https://github.com/aurelia-widgets/aurelia-kendoui/wiki/Introduction
