### ISSUE TITLE
Code style and code conventions

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia-widgets/aurelia-kendoui#9]
As we're going to be working closely together in the same codebase, we'll need to standardize some code formatting and code conventions.

There are many formatting options out there - some of them religious (tabs :) vs spaces :( ), etc. I think it's important to standardize on one of them and maybe even create a post-commit hook to handle formatting for us.

Additionally - linting - I've noticed that some mistakes have crept their way into some of the early commits. I was actually the cause of one of them. The core Aurelia projects use ESLint, which supports a plugin model that can handle multiple featuresets. It might be good to standardize upon a ruleset and adhere to it.

Finally - due to the mistakes that I made when pushing directly to the repository - I won't be making root code changes in this repo; I'll be making pull requests. It might be a good idea for everyone to do this as it provides opportunities for code review, etc.

Does anyone have a preferred code style guide that they like? Or, possibly, should we actually follow Aurelia's chosen style guide (two-space indent, cuddled parentheses, etc)?

Edit - As developers, we pretty much know a lot of this - but here, it's enumerated for reference: https://github.com/rwaldron/idiomatic.js

**Comment by adriatic** [comment]
Great issue - thanks for raising it Jedd. I would think that we are best advised to ask some of the aurelia core team members that are members of the [Aurelia-KendoUI](https://gitter.im/adriatic/Aurelia-KendoUI?at=5616d2a54e0fa3e55447b2a3) chat-room. I would also ask PWKad and or cmichaelgraham

**Comment by jedd-ahyoung** [comment]
I will say that Aurelia has its own code conventions (enumerated in its ESLint configuration) and its own style guide (that's in a document somewhere - I don't remember). While I suppose we could ask for an opinion, internal consistency is more important than anything.

I'll go ahead and edit the original post with some options.

**Comment by adriatic** [comment]
Agreed completely, thank you Jedd

**Comment by adriatic** [comment]
Received a comment from @PWKad
> @adriatic we decided to use eslint with most airbnb rules

**Comment by jedd-ahyoung** [comment]
Based on this Gitter chat:

on first - we cannot be official project of either organization since Telerik is not fully in open source, and we are. Aurelia (read Rob) is very strict in not allowing anything by stuff written by the core team to creep-in on it's own. There is however a firm statement (made by Rob to me) that anything and everything being created in Aurelia Community is a candidate to become part of "Aurelia proper" if it is created with format and style that would make such "marriage" simple enough. This is the reason for my attempts to make everything we do "Aurelia compatible"
If we are aiming for "Aurelia compatibility" to become part of "Aurelia proper", then that would decide some things such as our code style. If that's our goal, then we should adopt Aurelia's existing code standards; we should also adopt their commit message style for documentation purposes. I would propose that, due to this, we adopt the Aurelia guidelines for contributing


I think it's worth it to adopt Aurelia's guidelines. They've already been set and they're fairly robust.

**Comment by adriatic** [comment]
So, the task here is to collect the information and put it in a visible place

**Comment by jedd-ahyoung** [comment]
This is referenced in the PR with the `gulp lint` task and in the wiki here: https://github.com/aurelia-widgets/aurelia-kendoui/wiki/Development-Protocol
